version: '2'
services:
  explorer:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    depends_on:
      - mongo
      - monetaryunitd
    ports:
      - "8080:3030"
    environment:
      - APP_URL=testnetdns.monetaryunit.org
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=explorerdb
      - MONGO_USERNAME=iquidus
      - MONGO_PASSWORD=3xp!0reR
      - RPC_HOST=monetaryunitd
      - RPC_PORT=19904
      - RPC_USERNAME=slimshady
      - RPC_PASSWORD=mynameis
  mongo:
    image: mongo
    volumes:
       - ./docker/createmongouser.js:/docker-entrypoint-initdb.d/createmongouser.js:ro
       - mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=explorerdb
  monetaryunitd:
    image: muecoin/monetaryunitd
    command:
      -testnet
      -rpcallowip=*
    volumes:
      - monetaryunitdb:/home/coin/.monetaryunit
    ports:
      - "9904:19904"
    environment:
      - PPC_RPC_USER=${RPC_USERNAME}
      - PPC_RPC_PASSWORD=${RPC_PASSWORD}
volumes:
  mongodb:
  monetaryunitdb:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '/var/lib/mongodbbackup'
